### ISSUE TITLE
Linked page not available 

### ISSUE THREAD

**Issue by TommasoBendinelli** [tomsilver/policies_logic_programs#3]
The link https://github.com/tomsilver/policies_logic_programs/blob/master/generalization_grid_games is not available

**Comment by TommasoBendinelli** [comment]
Fixed by install generalization_grid_games from here https://github.com/tomsilver/generalization_grid_games

**Comment by tomsilver** [comment]
Whoops, thanks @TommasoBendinelli , the link in the readme is now fixed.
