### ISSUE TITLE
Issue when trying to play ReachTheStar

### ISSUE THREAD

**Issue by TommasoBendinelli** [tomsilver/policies_logic_programs#4]
AttributeError: module 'generalization_grid_games.envs.reach_for_the_star' has no attribute 'FLOOR' 
Fixed by adding to reach_for_the_start.py:
 FLOOR = 'floor' 

Unfortunately I get the following issue:
Exception has occurred: IndexError
index 12 is out of bounds for axis 0 with size 12 
at line 169 in expert_demostrations.py

**Comment by tomsilver** [comment]
@TommasoBendinelli thanks for filing the issue! Looks like an outdated version of the expert policy for RFTS was committed. This should now be fixed:

https://github.com/tomsilver/policies_logic_programs/commit/39a9b2c369d9468dce5c3733a0ecac6d82c32147

But let me know if you run into any more issues. Thanks again!
