### ISSUE TITLE
name 'ct' is not defined when trying to run CheckmateTactic

### ISSUE THREAD

**Issue by TommasoBendinelli** [tomsilver/policies_logic_programs#5]
Hello, 
I am trying to run the policy train and testing with Checkmate Tactics. Unfortunately I get: 
name "ct" is not defined at line 189 in pipeline.py

**Comment by TommasoBendinelli** [comment]
Fixed by adding in env_settings.py  import as ct

**Comment by tomsilver** [comment]
Thanks very much! Merged: https://github.com/tomsilver/policies_logic_programs/commit/232ba1ca66d38cf211f7e3b33ce47798841c2bcc
