### ISSUE TITLE
Code for running breakout

### ISSUE THREAD

**Issue by ManuelEberhardinger** [tomsilver/policies_logic_programs#6]
Hey Tom, 

I saw in the paper that you also applied this method to the Atari Breakout game. I have a looked a bit through the code but in this repo I only find the implementation for the grid games. 

Could you also publish the code for the Breakout game? 

Thanks in advance!

Manuel

**Comment by tomsilver** [comment]
Hi Manuel,

Thanks a lot for reaching out. I spent the last half hour trying to dig up the implementation for the Breakout game and unfortunately I haven't been able to find it. I believe the code was on an old laptop. I can't believe that we didn't commit it anywhere, and I'll keep looking for a while longer, but at the moment, it appears lost. This is terrible practice by me and I'm really sorry. If you are aiming to compare against it in a paper, you should of course feel free to say that the experiment was not reproducible. I'm very embarrassed and sorry again!

Sincerely,

Tom

**Comment by ManuelEberhardinger** [comment]
Don't worry man! I was just thinking about using this method to try out an idea I have, and the environment is more similar to the breakout environment than the grid environment. I should be able to implement it myself and this has the advantage of giving me a better understanding of your method. Thanks again and don't feel bad about it. Can happen to anyone! :)
